import { FoodItem } from '@/types/nutrition';

export const FOOD_DATABASE: FoodItem[] = [
  // --- CARBOHYDRATES ---
  {
    id: 'carb-oats',
    name: 'Rolled Oats',
    servingSize: 40,
    servingUnit: 'g',
    calories: 152,
    protein: 5.3,
    carbs: 27.0,
    fat: 2.7,
    fiber: 4.0,
    category: 'carbohydrates',
    dietTypes: ['vegetarian', 'non_vegetarian', 'vegan', 'eggetarian'],
    cuisines: ['international', 'mixed', 'indian'],
    allergens: [],
    glycemicIndex: 'low',
  },
  {
    id: 'carb-idli',
    name: 'Steamed Idli (2 pcs)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 140,
    protein: 4.0,
    carbs: 29.0,
    fat: 0.4,
    fiber: 2.0,
    category: 'carbohydrates',
    dietTypes: ['vegetarian', 'non_vegetarian', 'vegan', 'eggetarian'],
    cuisines: ['south_indian', 'indian', 'mixed'],
    allergens: [],
    glycemicIndex: 'medium',
  },
  {
    id: 'carb-dosa',
    name: 'Plain Crispy Dosa',
    servingSize: 80,
    servingUnit: 'g',
    calories: 168,
    protein: 3.8,
    carbs: 28.5,
    fat: 3.5,
    fiber: 1.8,
    category: 'carbohydrates',
    dietTypes: ['vegetarian', 'non_vegetarian', 'vegan', 'eggetarian'],
    cuisines: ['south_indian', 'indian', 'mixed'],
    allergens: [],
    glycemicIndex: 'medium',
  },
  {
    id: 'carb-poha',
    name: 'Vegetable Poha',
    servingSize: 150,
    servingUnit: 'g',
    calories: 180,
    protein: 3.5,
    carbs: 32.0,
    fat: 4.0,
    fiber: 2.5,
    category: 'carbohydrates',
    dietTypes: ['vegetarian', 'non_vegetarian', 'vegan', 'eggetarian'],
    cuisines: ['north_indian', 'indian', 'mixed'],
    allergens: [],
    glycemicIndex: 'medium',
  },
  {
    id: 'carb-upma',
    name: 'Vegetable Rava Upma',
    servingSize: 150,
    servingUnit: 'g',
    calories: 195,
    protein: 4.5,
    carbs: 33.0,
    fat: 5.0,
    fiber: 2.8,
    category: 'carbohydrates',
    dietTypes: ['vegetarian', 'non_vegetarian', 'vegan', 'eggetarian'],
    cuisines: ['south_indian', 'indian', 'mixed'],
    allergens: ['gluten'],
    glycemicIndex: 'medium',
  },
  {
    id: 'carb-roti',
    name: 'Whole Wheat Roti / Chapati',
    servingSize: 40,
    servingUnit: 'g',
    calories: 104,
    protein: 3.2,
    carbs: 21.0,
    fat: 0.8,
    fiber: 3.1,
    category: 'carbohydrates',
    dietTypes: ['vegetarian', 'non_vegetarian', 'vegan', 'eggetarian'],
    cuisines: ['north_indian', 'indian', 'south_indian', 'mixed'],
    allergens: ['gluten'],
    glycemicIndex: 'medium',
  },
  {
    id: 'carb-brown-rice',
    name: 'Cooked Brown Rice',
    servingSize: 150,
    servingUnit: 'g',
    calories: 165,
    protein: 3.5,
    carbs: 35.0,
    fat: 1.2,
    fiber: 2.8,
    category: 'carbohydrates',
    dietTypes: ['vegetarian', 'non_vegetarian', 'vegan', 'eggetarian'],
    cuisines: ['south_indian', 'north_indian', 'indian', 'international', 'mixed'],
    allergens: [],
    glycemicIndex: 'low',
  },
  {
    id: 'carb-white-rice',
    name: 'Steamed White Basmati Rice',
    servingSize: 150,
    servingUnit: 'g',
    calories: 195,
    protein: 4.0,
    carbs: 43.0,
    fat: 0.5,
    fiber: 1.0,
    category: 'carbohydrates',
    dietTypes: ['vegetarian', 'non_vegetarian', 'vegan', 'eggetarian'],
    cuisines: ['south_indian', 'north_indian', 'indian', 'mixed'],
    allergens: [],
    glycemicIndex: 'high',
  },
  {
    id: 'carb-quinoa',
    name: 'Cooked Quinoa',
    servingSize: 140,
    servingUnit: 'g',
    calories: 168,
    protein: 6.0,
    carbs: 29.5,
    fat: 2.6,
    fiber: 3.8,
    category: 'carbohydrates',
    dietTypes: ['vegetarian', 'non_vegetarian', 'vegan', 'eggetarian'],
    cuisines: ['international', 'mixed'],
    allergens: [],
    glycemicIndex: 'low',
  },
  {
    id: 'carb-sweet-potato',
    name: 'Boiled Sweet Potato',
    servingSize: 130,
    servingUnit: 'g',
    calories: 112,
    protein: 2.0,
    carbs: 26.0,
    fat: 0.1,
    fiber: 3.9,
    category: 'carbohydrates',
    dietTypes: ['vegetarian', 'non_vegetarian', 'vegan', 'eggetarian'],
    cuisines: ['international', 'indian', 'mixed'],
    allergens: [],
    glycemicIndex: 'low',
  },
  {
    id: 'carb-whole-wheat-bread',
    name: 'Whole Grain Bread (2 slices)',
    servingSize: 60,
    servingUnit: 'g',
    calories: 148,
    protein: 6.0,
    carbs: 26.0,
    fat: 1.8,
    fiber: 4.0,
    category: 'carbohydrates',
    dietTypes: ['vegetarian', 'non_vegetarian', 'vegan', 'eggetarian'],
    cuisines: ['international', 'mixed'],
    allergens: ['gluten'],
    glycemicIndex: 'medium',
  },

  // --- PROTEINS ---
  {
    id: 'prot-chicken-breast',
    name: 'Grilled Chicken Breast',
    servingSize: 120,
    servingUnit: 'g',
    calories: 198,
    protein: 37.0,
    carbs: 0.0,
    fat: 4.3,
    fiber: 0.0,
    category: 'protein',
    dietTypes: ['non_vegetarian'],
    cuisines: ['international', 'north_indian', 'south_indian', 'indian', 'mixed'],
    allergens: [],
  },
  {
    id: 'prot-fish-fillet',
    name: 'Pan-Seared Fish Fillet',
    servingSize: 120,
    servingUnit: 'g',
    calories: 160,
    protein: 30.0,
    carbs: 0.0,
    fat: 3.8,
    fiber: 0.0,
    category: 'protein',
    dietTypes: ['non_vegetarian'],
    cuisines: ['south_indian', 'north_indian', 'international', 'mixed'],
    allergens: ['seafood'],
  },
  {
    id: 'prot-eggs-boiled',
    name: 'Boiled Whole Eggs (2 large)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 155,
    protein: 13.0,
    carbs: 1.1,
    fat: 11.0,
    fiber: 0.0,
    category: 'protein',
    dietTypes: ['non_vegetarian', 'eggetarian'],
    cuisines: ['international', 'indian', 'north_indian', 'south_indian', 'mixed'],
    allergens: ['eggs'],
  },
  {
    id: 'prot-egg-whites',
    name: 'Egg Whites (3 whites)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 52,
    protein: 11.0,
    carbs: 0.7,
    fat: 0.2,
    fiber: 0.0,
    category: 'protein',
    dietTypes: ['non_vegetarian', 'eggetarian'],
    cuisines: ['international', 'indian', 'mixed'],
    allergens: ['eggs'],
  },
  {
    id: 'prot-paneer',
    name: 'Low-Fat Fresh Paneer',
    servingSize: 80,
    servingUnit: 'g',
    calories: 180,
    protein: 18.0,
    carbs: 3.5,
    fat: 10.0,
    fiber: 0.0,
    category: 'protein',
    dietTypes: ['vegetarian', 'non_vegetarian', 'eggetarian'],
    cuisines: ['north_indian', 'indian', 'south_indian', 'mixed'],
    allergens: ['dairy'],
  },
  {
    id: 'prot-tofu',
    name: 'Organic Firm Tofu',
    servingSize: 100,
    servingUnit: 'g',
    calories: 120,
    protein: 14.0,
    carbs: 2.5,
    fat: 6.5,
    fiber: 1.5,
    category: 'protein',
    dietTypes: ['vegetarian', 'non_vegetarian', 'vegan', 'eggetarian'],
    cuisines: ['international', 'mixed', 'indian'],
    allergens: ['soy'],
  },
  {
    id: 'prot-yellow-dal',
    name: 'Cooked Moong / Toor Dal',
    servingSize: 150,
    servingUnit: 'g',
    calories: 165,
    protein: 10.5,
    carbs: 24.0,
    fat: 2.5,
    fiber: 6.5,
    category: 'protein',
    dietTypes: ['vegetarian', 'non_vegetarian', 'vegan', 'eggetarian'],
    cuisines: ['south_indian', 'north_indian', 'indian', 'mixed'],
    allergens: [],
  },
  {
    id: 'prot-rajma',
    name: 'Rajma Masala (Kidney Beans)',
    servingSize: 160,
    servingUnit: 'g',
    calories: 190,
    protein: 11.5,
    carbs: 30.0,
    fat: 2.8,
    fiber: 8.5,
    category: 'protein',
    dietTypes: ['vegetarian', 'non_vegetarian', 'vegan', 'eggetarian'],
    cuisines: ['north_indian', 'indian', 'mixed'],
    allergens: [],
  },
  {
    id: 'prot-chole',
    name: 'Chole / Spiced Chickpeas',
    servingSize: 150,
    servingUnit: 'g',
    calories: 210,
    protein: 12.0,
    carbs: 32.0,
    fat: 4.0,
    fiber: 9.0,
    category: 'protein',
    dietTypes: ['vegetarian', 'non_vegetarian', 'vegan', 'eggetarian'],
    cuisines: ['north_indian', 'indian', 'mixed', 'international'],
    allergens: [],
  },
  {
    id: 'prot-sambar',
    name: 'Vegetable Sambar Dal',
    servingSize: 180,
    servingUnit: 'ml',
    calories: 130,
    protein: 6.5,
    carbs: 19.0,
    fat: 2.5,
    fiber: 5.0,
    category: 'protein',
    dietTypes: ['vegetarian', 'non_vegetarian', 'vegan', 'eggetarian'],
    cuisines: ['south_indian', 'indian', 'mixed'],
    allergens: [],
  },
  {
    id: 'prot-greek-yogurt',
    name: 'Greek Yogurt / Thick Curd',
    servingSize: 150,
    servingUnit: 'g',
    calories: 120,
    protein: 15.0,
    carbs: 6.0,
    fat: 2.5,
    fiber: 0.0,
    category: 'protein',
    dietTypes: ['vegetarian', 'non_vegetarian', 'eggetarian'],
    cuisines: ['south_indian', 'north_indian', 'indian', 'international', 'mixed'],
    allergens: ['dairy'],
  },
  {
    id: 'prot-soya-chunks',
    name: 'Cooked Soya Chunks Curry',
    servingSize: 120,
    servingUnit: 'g',
    calories: 160,
    protein: 22.0,
    carbs: 11.0,
    fat: 1.5,
    fiber: 6.0,
    category: 'protein',
    dietTypes: ['vegetarian', 'non_vegetarian', 'vegan', 'eggetarian'],
    cuisines: ['north_indian', 'indian', 'south_indian', 'mixed'],
    allergens: ['soy'],
  },

  // --- FRUITS ---
  {
    id: 'fruit-banana',
    name: 'Fresh Banana',
    servingSize: 100,
    servingUnit: 'g',
    calories: 89,
    protein: 1.1,
    carbs: 23.0,
    fat: 0.3,
    fiber: 2.6,
    category: 'fruits',
    dietTypes: ['vegetarian', 'non_vegetarian', 'vegan', 'eggetarian'],
    cuisines: ['south_indian', 'north_indian', 'indian', 'international', 'mixed'],
    allergens: [],
  },
  {
    id: 'fruit-apple',
    name: 'Crisp Apple',
    servingSize: 120,
    servingUnit: 'g',
    calories: 62,
    protein: 0.3,
    carbs: 16.0,
    fat: 0.2,
    fiber: 3.0,
    category: 'fruits',
    dietTypes: ['vegetarian', 'non_vegetarian', 'vegan', 'eggetarian'],
    cuisines: ['international', 'indian', 'north_indian', 'south_indian', 'mixed'],
    allergens: [],
  },
  {
    id: 'fruit-papaya',
    name: 'Fresh Papaya Slices',
    servingSize: 150,
    servingUnit: 'g',
    calories: 65,
    protein: 0.7,
    carbs: 16.0,
    fat: 0.4,
    fiber: 2.7,
    category: 'fruits',
    dietTypes: ['vegetarian', 'non_vegetarian', 'vegan', 'eggetarian'],
    cuisines: ['south_indian', 'indian', 'mixed'],
    allergens: [],
  },
  {
    id: 'fruit-pomegranate',
    name: 'Pomegranate Seeds',
    servingSize: 80,
    servingUnit: 'g',
    calories: 66,
    protein: 1.3,
    carbs: 15.0,
    fat: 0.9,
    fiber: 3.2,
    category: 'fruits',
    dietTypes: ['vegetarian', 'non_vegetarian', 'vegan', 'eggetarian'],
    cuisines: ['indian', 'international', 'north_indian', 'mixed'],
    allergens: [],
  },
  {
    id: 'fruit-orange',
    name: 'Sweet Orange',
    servingSize: 130,
    servingUnit: 'g',
    calories: 62,
    protein: 1.2,
    carbs: 15.4,
    fat: 0.2,
    fiber: 3.1,
    category: 'fruits',
    dietTypes: ['vegetarian', 'non_vegetarian', 'vegan', 'eggetarian'],
    cuisines: ['international', 'indian', 'mixed'],
    allergens: [],
  },
  {
    id: 'fruit-watermelon',
    name: 'Watermelon Cubes',
    servingSize: 200,
    servingUnit: 'g',
    calories: 60,
    protein: 1.2,
    carbs: 15.0,
    fat: 0.3,
    fiber: 0.8,
    category: 'fruits',
    dietTypes: ['vegetarian', 'non_vegetarian', 'vegan', 'eggetarian'],
    cuisines: ['south_indian', 'indian', 'international', 'mixed'],
    allergens: [],
  },
  {
    id: 'fruit-guava',
    name: 'Fresh Guava',
    servingSize: 100,
    servingUnit: 'g',
    calories: 68,
    protein: 2.6,
    carbs: 14.3,
    fat: 0.9,
    fiber: 5.4,
    category: 'fruits',
    dietTypes: ['vegetarian', 'non_vegetarian', 'vegan', 'eggetarian'],
    cuisines: ['indian', 'south_indian', 'mixed'],
    allergens: [],
  },

  // --- VEGETABLES ---
  {
    id: 'veg-spinach',
    name: 'Steamed / Sauteed Palak (Spinach)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 28,
    protein: 3.0,
    carbs: 3.8,
    fat: 0.5,
    fiber: 2.4,
    category: 'vegetables',
    dietTypes: ['vegetarian', 'non_vegetarian', 'vegan', 'eggetarian'],
    cuisines: ['north_indian', 'south_indian', 'indian', 'international', 'mixed'],
    allergens: [],
  },
  {
    id: 'veg-broccoli',
    name: 'Steamed Broccoli Florets',
    servingSize: 100,
    servingUnit: 'g',
    calories: 34,
    protein: 2.8,
    carbs: 6.6,
    fat: 0.4,
    fiber: 2.6,
    category: 'vegetables',
    dietTypes: ['vegetarian', 'non_vegetarian', 'vegan', 'eggetarian'],
    cuisines: ['international', 'mixed'],
    allergens: [],
  },
  {
    id: 'veg-bhindi',
    name: 'Spiced Bhindi (Okra) Fry',
    servingSize: 100,
    servingUnit: 'g',
    calories: 65,
    protein: 2.0,
    carbs: 7.5,
    fat: 3.0,
    fiber: 3.2,
    category: 'vegetables',
    dietTypes: ['vegetarian', 'non_vegetarian', 'vegan', 'eggetarian'],
    cuisines: ['north_indian', 'south_indian', 'indian', 'mixed'],
    allergens: [],
  },
  {
    id: 'veg-cucumber-salad',
    name: 'Cucumber & Tomato Salad',
    servingSize: 120,
    servingUnit: 'g',
    calories: 22,
    protein: 1.0,
    carbs: 4.5,
    fat: 0.2,
    fiber: 1.8,
    category: 'vegetables',
    dietTypes: ['vegetarian', 'non_vegetarian', 'vegan', 'eggetarian'],
    cuisines: ['south_indian', 'north_indian', 'indian', 'international', 'mixed'],
    allergens: [],
  },
  {
    id: 'veg-mixed-sabzi',
    name: 'Mixed Veg Curry (Beans, Carrot, Peas)',
    servingSize: 120,
    servingUnit: 'g',
    calories: 75,
    protein: 2.8,
    carbs: 11.0,
    fat: 2.2,
    fiber: 4.0,
    category: 'vegetables',
    dietTypes: ['vegetarian', 'non_vegetarian', 'vegan', 'eggetarian'],
    cuisines: ['north_indian', 'south_indian', 'indian', 'mixed'],
    allergens: [],
  },

  // --- NUTS & SEEDS ---
  {
    id: 'nut-almonds',
    name: 'Raw / Soaked Almonds',
    servingSize: 15,
    servingUnit: 'g',
    calories: 87,
    protein: 3.2,
    carbs: 3.2,
    fat: 7.5,
    fiber: 1.8,
    category: 'nuts_seeds',
    dietTypes: ['vegetarian', 'non_vegetarian', 'vegan', 'eggetarian'],
    cuisines: ['south_indian', 'north_indian', 'indian', 'international', 'mixed'],
    allergens: ['nuts'],
  },
  {
    id: 'nut-walnuts',
    name: 'Walnut Halves',
    servingSize: 15,
    servingUnit: 'g',
    calories: 98,
    protein: 2.3,
    carbs: 2.0,
    fat: 9.8,
    fiber: 1.0,
    category: 'nuts_seeds',
    dietTypes: ['vegetarian', 'non_vegetarian', 'vegan', 'eggetarian'],
    cuisines: ['international', 'indian', 'north_indian', 'mixed'],
    allergens: ['nuts'],
  },
  {
    id: 'nut-chia-seeds',
    name: 'Chia Seeds',
    servingSize: 10,
    servingUnit: 'g',
    calories: 49,
    protein: 1.7,
    carbs: 4.2,
    fat: 3.1,
    fiber: 3.4,
    category: 'nuts_seeds',
    dietTypes: ['vegetarian', 'non_vegetarian', 'vegan', 'eggetarian'],
    cuisines: ['international', 'mixed', 'indian'],
    allergens: [],
  },
  {
    id: 'nut-roasted-peanuts',
    name: 'Roasted Peanuts',
    servingSize: 20,
    servingUnit: 'g',
    calories: 115,
    protein: 5.2,
    carbs: 3.2,
    fat: 9.8,
    fiber: 1.8,
    category: 'nuts_seeds',
    dietTypes: ['vegetarian', 'non_vegetarian', 'vegan', 'eggetarian'],
    cuisines: ['south_indian', 'north_indian', 'indian', 'international', 'mixed'],
    allergens: ['nuts'],
  },

  // --- DAIRY / LIQUIDS & HEALTHY FATS ---
  {
    id: 'dairy-milk',
    name: 'Toned Cow Milk',
    servingSize: 200,
    servingUnit: 'ml',
    calories: 120,
    protein: 6.4,
    carbs: 9.6,
    fat: 6.0,
    fiber: 0.0,
    category: 'dairy_alternatives',
    dietTypes: ['vegetarian', 'non_vegetarian', 'eggetarian'],
    cuisines: ['south_indian', 'north_indian', 'indian', 'international', 'mixed'],
    allergens: ['dairy'],
  },
  {
    id: 'dairy-almond-milk',
    name: 'Unsweetened Almond Milk',
    servingSize: 200,
    servingUnit: 'ml',
    calories: 30,
    protein: 1.0,
    carbs: 1.0,
    fat: 2.5,
    fiber: 0.5,
    category: 'dairy_alternatives',
    dietTypes: ['vegetarian', 'non_vegetarian', 'vegan', 'eggetarian'],
    cuisines: ['international', 'mixed'],
    allergens: ['nuts'],
  },
  {
    id: 'dairy-soy-milk',
    name: 'Unsweetened Soy Milk',
    servingSize: 200,
    servingUnit: 'ml',
    calories: 80,
    protein: 7.0,
    carbs: 4.0,
    fat: 4.0,
    fiber: 1.0,
    category: 'dairy_alternatives',
    dietTypes: ['vegetarian', 'non_vegetarian', 'vegan', 'eggetarian'],
    cuisines: ['international', 'mixed'],
    allergens: ['soy'],
  },
  {
    id: 'fat-olive-oil',
    name: 'Extra Virgin Olive Oil',
    servingSize: 5,
    servingUnit: 'ml',
    calories: 44,
    protein: 0.0,
    carbs: 0.0,
    fat: 5.0,
    fiber: 0.0,
    category: 'fats_oils',
    dietTypes: ['vegetarian', 'non_vegetarian', 'vegan', 'eggetarian'],
    cuisines: ['international', 'mixed'],
    allergens: [],
  },
  {
    id: 'fat-ghee',
    name: 'Pure Desi Ghee',
    servingSize: 5,
    servingUnit: 'g',
    calories: 45,
    protein: 0.0,
    carbs: 0.0,
    fat: 5.0,
    fiber: 0.0,
    category: 'fats_oils',
    dietTypes: ['vegetarian', 'non_vegetarian', 'eggetarian'],
    cuisines: ['north_indian', 'south_indian', 'indian', 'mixed'],
    allergens: ['dairy'],
  },
  {
    id: 'fat-peanut-butter',
    name: 'Natural Peanut Butter',
    servingSize: 15,
    servingUnit: 'g',
    calories: 90,
    protein: 4.0,
    carbs: 3.0,
    fat: 8.0,
    fiber: 1.0,
    category: 'fats_oils',
    dietTypes: ['vegetarian', 'non_vegetarian', 'vegan', 'eggetarian'],
    cuisines: ['international', 'mixed'],
    allergens: ['nuts'],
  },
  {
    id: 'prot-buttermilk',
    name: 'Spiced Buttermilk (Chaas)',
    servingSize: 200,
    servingUnit: 'ml',
    calories: 50,
    protein: 3.0,
    carbs: 5.0,
    fat: 1.8,
    fiber: 0.0,
    category: 'dairy_alternatives',
    dietTypes: ['vegetarian', 'non_vegetarian', 'eggetarian'],
    cuisines: ['south_indian', 'north_indian', 'indian', 'mixed'],
    allergens: ['dairy'],
  },
  {
    id: 'prot-coconut-chutney',
    name: 'Fresh Coconut Chutney',
    servingSize: 30,
    servingUnit: 'g',
    calories: 60,
    protein: 1.0,
    carbs: 2.0,
    fat: 5.5,
    fiber: 1.2,
    category: 'fats_oils',
    dietTypes: ['vegetarian', 'non_vegetarian', 'vegan', 'eggetarian'],
    cuisines: ['south_indian', 'indian', 'mixed'],
    allergens: [],
  },
  {
    id: 'prot-mint-chutney',
    name: 'Mint & Coriander Chutney',
    servingSize: 30,
    servingUnit: 'g',
    calories: 20,
    protein: 0.8,
    carbs: 2.5,
    fat: 0.5,
    fiber: 1.0,
    category: 'vegetables',
    dietTypes: ['vegetarian', 'non_vegetarian', 'vegan', 'eggetarian'],
    cuisines: ['north_indian', 'indian', 'mixed'],
    allergens: [],
  },
];

/**
 * Filter foods based on user dietary preference and allergy restrictions.
 */
export function getFilteredFoods(
  dietPreference: FoodItem['dietTypes'][number],
  restrictions: FoodItem['allergens'] = [],
  cuisine?: FoodItem['cuisines'][number]
): FoodItem[] {
  return FOOD_DATABASE.filter((food) => {
    // Check diet compatibility
    if (!food.dietTypes.includes(dietPreference)) {
      return false;
    }

    // Check allergy restrictions (strict rejection)
    if (restrictions.length > 0) {
      const hasAllergen = food.allergens.some((allergen) => restrictions.includes(allergen));
      if (hasAllergen) {
        return false;
      }
    }

    // Check cuisine preference if provided
    if (cuisine && food.cuisines.length > 0 && !food.cuisines.includes(cuisine) && !food.cuisines.includes('mixed')) {
      return false;
    }

    return true;
  });
}
